CREATE TABLE "hackyeah2025_company" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hackyeah2025_company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"companyName" varchar(255),
	"location" varchar(255),
	"description" text
);
--> statement-breakpoint
CREATE TABLE "hackyeah2025_coordinator" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hackyeah2025_coordinator_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"firstName" varchar(255),
	"lastName" varchar(255),
	"school" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "hackyeah2025_volunteer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hackyeah2025_volunteer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"firstName" varchar(255),
	"lastName" varchar(255),
	"is_of_age" boolean
);
--> statement-breakpoint
ALTER TABLE "hackyeah2025_user" ADD COLUMN "role" varchar(50) DEFAULT 'wolontariusz' NOT NULL;--> statement-breakpoint
ALTER TABLE "hackyeah2025_user" ADD COLUMN "profileCompleted" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "hackyeah2025_company" ADD CONSTRAINT "hackyeah2025_company_userId_hackyeah2025_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hackyeah2025_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hackyeah2025_coordinator" ADD CONSTRAINT "hackyeah2025_coordinator_userId_hackyeah2025_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hackyeah2025_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hackyeah2025_volunteer" ADD CONSTRAINT "hackyeah2025_volunteer_userId_hackyeah2025_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hackyeah2025_user"("id") ON DELETE no action ON UPDATE no action;