CREATE TABLE "hackyeah2025_application" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hackyeah2025_application_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"volunteerId" integer NOT NULL,
	"eventId" integer NOT NULL,
	"message" text,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hackyeah2025_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hackyeah2025_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"organizerName" varchar(255) NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb,
	"thumbnail" varchar(500),
	"latitude" real,
	"longitude" real,
	"startDate" timestamp with time zone,
	"endDate" timestamp with time zone,
	"workload" jsonb DEFAULT '[]'::jsonb,
	"form" jsonb DEFAULT '[]'::jsonb,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
DROP TABLE "hackyeah2025_post" CASCADE;--> statement-breakpoint
ALTER TABLE "hackyeah2025_application" ADD CONSTRAINT "hackyeah2025_application_volunteerId_hackyeah2025_volunteer_id_fk" FOREIGN KEY ("volunteerId") REFERENCES "public"."hackyeah2025_volunteer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hackyeah2025_application" ADD CONSTRAINT "hackyeah2025_application_eventId_hackyeah2025_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."hackyeah2025_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hackyeah2025_event" ADD CONSTRAINT "hackyeah2025_event_createdById_hackyeah2025_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."hackyeah2025_user"("id") ON DELETE no action ON UPDATE no action;